### ISSUE TITLE
I2P Support

### ISSUE THREAD

**Issue by HardenedSteel** [ditatompel/xmr-remote-nodes#148]
Allow listing I2P nodes. Similar project with I2P support: https://monero.fail/?chain=monero&network=mainnet&i2p=on

**Comment by ditatompel** [comment]
I'm currently rewriting the frontend to reduce external dependencies. Once that's done, I'll try to add I2P support.
Thanks

**Comment by ditatompel** [comment]
Hi, @HardenedSteel, thanks for your patience.

I would like to inform you that I have implemented I2P nodes monitoring and have also tried adding an I2P node to the website https://xmr.ditatompel.com/remote-nodes?protocol=i2p.

Please let me know if there are any shortcomings that need to be fixed. Thanks!

**Comment by ditatompel** [comment]
Hi,

I close this issue, feel free to re-open if needed. Thanks.
